### ISSUE TITLE
Warning messages during installation

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/flarum_ynh#147]
**Describe the bug**
At the end of the flarum installation, there is an error regarding the yunohost diagnosis command (`yunohost tools diagnosis` instead of `yunohost diagnosis` 
(Here: https://github.com/YunoHost-Apps/flarum_ynh/blob/f811e7f37c8fd428343501f72bc1d2c3e7e44916/scripts/experimental_helpers/ynh_send_readme_to_admin#L85)

There is also several warnings regarding the usage of composer as root user and one regarding the french package (`Attention : Package milescellar/lang-french is abandoned, you should avoid using it. Use qiaeru/lang-french instead.`) but I don't know if it's relevant.

**Versions**
- YunoHost version:
```
yunohost: 
  repo: stable
  version: 3.8.4.9
yunohost-admin: 
  repo: stable
  version: 3.8.3.4
moulinette: 
  repo: stable
  version: 3.8.1.2
ssowat: 
  repo: stable
  version: 3.8.0.2
```

- Using, or trying to install package version/branch:
```
name: Flarum
version: 0.1.0-beta.13~ynh1
```

**To Reproduce**
`yunohost app install flarum`

**Logs**
https://paste.yunohost.org/raw/dorikasiru

Anyway, thanks for updating this package :heart:
