### ISSUE TITLE
Cannot load admin panel on a fresh install

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/flarum_ynh#163]
**Describe the bug**
On a fresh install (YNH and Flarum), after logging in via SSOWAT to my admin user account, when I click on "Administration", a new tab opens, with the title of the forum and a blank page with a message on a yellow background indicating: 
> Une erreur est survenue lors de la tentative de chargement de la version complète de ce site. Veuillez purger le cache de votre navigateur et rafraîchir cette page pour tenter de corriger cette erreur.

Flarum is installed on another domain (path: '/') than main YNH domain.

I tested on several browsers, tried to purge the cache... same error.

No error in nginx log

Some error on web console: 

Chromium: 
> (index):93 
> Uncaught TypeError: Cannot set property 'tituspijean-auth-ssowat' of undefined
>     at index.js:6
>     at Application.js:168
>     at Array.forEach (<anonymous>)
>     at e.boot (Application.js:168)
>     at (index):88

Firefox:

> Uncaught TypeError: app.extensionSettings is undefined
>     js index.js:6
>     boot Application.js:168
>     boot Application.js:168
>     <anonymous> admin:88
> index.js:6:1
>     js index.js:6
>     boot Application.js:168
>     forEach self-hosted:206
>     boot Application.js:168
>     <anonyme> admin:88
> 
> 

**Versions**
- YunoHost version:
```
yunohost: 
  repo: stable
  version: 4.1.7.4
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
```

**To Reproduce**
- Install Flarum on another domain than YNH domain ; path: '/'
- Log in with the admin user defined at Flarum installation using SSOWAT
- Click on your name and chose "Administration" (or go to flarum.domain/admin)
